site_name: Lurch Deductive Engine Documentation
pages:
- Home: index.md
- Design Plans:
    - Overview: design-overview.md
    - Phase 1, Structures: phase1-structures.md
    - Phase 2, Basic Validation: phase2-validation.md
    - Phase 3, The Client: phase3-client.md
    - Phase 4, Dependencies: phase4-dependencies.md
    - Phase 5, Background Queue: phase5-background.md
    - Phase 6, String Matching: phase6-strings.md
    - Phase 7, Theorems and Proofs: phase7-theorems.md
    - Phase 8, Expression Trees: phase8-expressions.md
    - Phase 9, Parsing Rules: phase9-parsing.md
    - Phase 10, Declarations: phase10-declarations.md
    - Phase 11, Bonus Features: phase11-features.md
    - Ideas Archive: ideas.md
- API Documentation:
    - Overview: api-overview.md
    - Structures: api-structures.md
    - The LDE: api-lde.md
dev_addr: 127.0.0.1:8888
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
    - pymdownx.tasklist
