site_name: Lurch Deductive Engine Documentation
pages:
- Home: index.md
- Design Plans:
    - Overview: design-overview.md
    - Phase 1, Structures: phase1-structures.md
    - Phase 2, The Input Tree: phase2-input-tree.md
    - Phase 3, Interpretation: phase3-interpretation.md
    - Phase 4, Validation: phase4-validation.md
    - Phase N, List of outdated phases: phaseN-archive.md
    - Enhancements for Later: enhancements.md
    - Ideas Archive: ideas.md
- API Documentation:
    - Overview: api-overview.md
    - The LDE: api-lde.md
    - Structures: api-structures.md
    - Labels: api-labels.md
    - Reasons: api-reasons.md
dev_addr: 127.0.0.1:8888
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
    - pymdownx.tasklist
